import { Body, ConflictException, Controller, ForbiddenException, Get, NotFoundException, Param, Post, UseGuards } from '@nestjs/common';import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';import { IsString, IsUUID, MaxLength } from 'class-validator';import { CurrentUser } from '../common/decorators/current-user.decorator';import { JwtGuard } from '../common/guards/jwt.guard';import { PrismaService } from '../prisma/prisma.service';import { WalletService } from '../wallet/wallet.service';
class SendGiftDto { @IsUUID() receiverId!:string; @IsString() @MaxLength(100) idempotencyKey!:string; }
@ApiTags('Digital gifts') @Controller('gifts') export class GiftsController {
  constructor(private readonly db:PrismaService,private readonly wallets:WalletService){}
  @Get() list(){return this.db.digitalGift.findMany({where:{active:true}})}
  @ApiBearerAuth() @UseGuards(JwtGuard) @Post(':id/send') send(@Param('id')id:string,@Body()d:SendGiftDto,@CurrentUser()u:{sub:string}){
    return this.wallets.transaction(async tx=>{const key=`gift:${u.sub}:${d.idempotencyKey}`,prior=await tx.walletLedger.findUnique({where:{idempotencyKey:`${key}:purchase`}});if(prior)return{sent:true,duplicate:true,receiverId:d.receiverId};if(u.sub===d.receiverId)throw new ConflictException('Cannot send a gift to yourself');const blocked=await tx.block.findFirst({where:{OR:[{blockerId:u.sub,blockedUserId:d.receiverId},{blockerId:d.receiverId,blockedUserId:u.sub}]}});if(blocked)throw new ForbiddenException('Gifting is blocked');const gift=await tx.digitalGift.findUnique({where:{id}}),vendor=await tx.vendorProfile.findUnique({where:{userId:d.receiverId}});if(!gift||!gift.active)throw new NotFoundException('Gift not found');if(!vendor||vendor.status!=='APPROVED')throw new NotFoundException('Recipient vendor not found');await this.wallets.debitPurchased(tx,{userId:u.sub,type:'GIFT_PURCHASE',direction:'DEBIT',amount:gift.pointPrice,referenceType:'DIGITAL_GIFT',referenceId:gift.id,description:`Sent ${gift.name}`,idempotencyKey:`${key}:purchase`});const vendorAmount=Math.floor(gift.pointPrice*gift.vendorPercent/100),platformAmount=gift.pointPrice-vendorAmount;await this.wallets.creditPendingEarning(tx,d.receiverId,vendorAmount,key,'GIFT');await this.wallets.platformCommission(tx,platformAmount,'DIGITAL_GIFT',key,'Digital gift commission');await tx.earning.create({data:{vendorId:vendor.id,sourceType:'GIFT',sourceId:key,grossAmount:gift.pointPrice,vendorAmount,platformAmount,availableAt:new Date(Date.now()+7*86400000)}});await tx.notification.create({data:{userId:d.receiverId,type:'GIFT',title:`You received ${gift.name}`,body:`A supporter sent you ${gift.name}.`,data:{giftId:gift.id}}});return{sent:true,gift:gift.name,receiverId:d.receiverId,vendorAmount};});
  }
}
