import{ConflictException,ForbiddenException,Injectable,NotFoundException}from'@nestjs/common';import{PrismaService}from'../prisma/prisma.service';import type{CreateReviewDto,ModerateReviewReportDto,ReportReviewDto,ReviewVisibilityDto}from'./reviews.controller';
@Injectable()export class ReviewsService{constructor(private readonly db:PrismaService){}
  list(vendorId:string,cursor?:string){return this.db.review.findMany({where:{vendorId,status:'VISIBLE'},include:{reviewer:{select:{profile:{select:{displayName:true,avatarUrl:true}}}}},orderBy:{createdAt:'desc'},take:30,...(cursor?{skip:1,cursor:{id:cursor}}:{})})}
  create(userId:string,dto:CreateReviewDto){return this.db.$transaction(async tx=>{const call=await tx.callSession.findUnique({where:{id:dto.callId},include:{vendor:true,review:true}});if(!call||call.callerId!==userId)throw new ForbiddenException('Only the caller can review this interaction');if(call.status!=='COMPLETED'||call.billedSeconds<=0)throw new ConflictException('Only completed interactions can be reviewed');if(call.review)throw new ConflictException('This interaction has already been reviewed');const review=await tx.review.create({data:{reviewerId:userId,vendorId:call.vendorId,...dto,comment:dto.comment?.trim()||null}});await this.recalculate(tx,call.vendorId);await tx.notification.create({data:{userId:call.vendor.userId,type:'REVIEW',title:'New customer review',body:`You received a ${dto.rating}-star review.`,data:{reviewId:review.id,callId:call.id}}});return review})}
  async report(reporterId:string,reviewId:string,dto:ReportReviewDto){const review=await this.db.review.findUnique({where:{id:reviewId}});if(!review||review.status!=='VISIBLE')throw new NotFoundException('Review not found');if(review.reviewerId===reporterId)throw new ConflictException('You cannot report your own review');try{return await this.db.reviewReport.create({data:{reviewId,reporterId,reason:dto.reason,details:dto.details?.trim()}})}catch{throw new ConflictException('You already reported this review')}}
  reportQueue(){return this.db.reviewReport.findMany({where:{status:'OPEN'},include:{review:{include:{reviewer:{select:{profile:{select:{displayName:true,username:true}}}},vendor:{select:{id:true,user:{select:{profile:{select:{displayName:true}}}}}}}},reporter:{select:{profile:{select:{displayName:true,username:true}}}}},orderBy:{createdAt:'asc'},take:250})}
  async moderateReport(actor:{sub:string;role:string},id:string,dto:ModerateReviewReportDto){return this.db.$transaction(async tx=>{const report=await tx.reviewReport.findUniqueOrThrow({where:{id},include:{review:true}});if(report.status!=='OPEN')throw new ConflictException('Report is already reviewed');const reviewStatus=dto.reviewAction==='HIDE'?'HIDDEN':'VISIBLE';await tx.review.update({where:{id:report.reviewId},data:{status:reviewStatus}});await tx.reviewReport.update({where:{id},data:{status:dto.status,resolution:dto.resolution,reviewedBy:actor.sub,reviewedAt:new Date()}});await this.recalculate(tx,report.review.vendorId);await tx.auditLog.create({data:{actorId:actor.sub,actorRole:actor.role,action:'REVIEW_REPORT_MODERATED',entityType:'REVIEW',entityId:report.reviewId,newValue:{reportId:id,status:dto.status,reviewAction:dto.reviewAction,resolution:dto.resolution}}});if(dto.reviewAction==='HIDE')await tx.notification.create({data:{userId:report.review.reviewerId,type:'MODERATION',title:'Review hidden',body:'A review was hidden after a moderation assessment.',data:{reviewId:report.reviewId}}});return{moderated:true,reviewStatus}})}
  async visibility(actor:{sub:string;role:string},id:string,dto:ReviewVisibilityDto){return this.db.$transaction(async tx=>{const review=await tx.review.update({where:{id},data:{status:dto.status}});await this.recalculate(tx,review.vendorId);await tx.auditLog.create({data:{actorId:actor.sub,actorRole:actor.role,action:'REVIEW_VISIBILITY_CHANGED',entityType:'REVIEW',entityId:id,newValue:{status:dto.status,reason:dto.reason}}});return review})}
  private async recalculate(tx:any,vendorId:string){const aggregate=await tx.review.aggregate({where:{vendorId,status:'VISIBLE'},_avg:{rating:true},_count:true});await tx.vendorProfile.update({where:{id:vendorId},data:{averageRating:aggregate._avg.rating??0}})}
}
