ALTER TABLE "LiveSession" ADD COLUMN IF NOT EXISTS "virtualMode" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "LiveSession" ADD COLUMN IF NOT EXISTS "virtualAvatar" TEXT NOT NULL DEFAULT 'fox';
ALTER TABLE "LiveSession" ADD COLUMN IF NOT EXISTS "activeGameId" TEXT;

ALTER TABLE "LivePk" ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'SOLO';
ALTER TABLE "LivePk" ADD COLUMN IF NOT EXISTS "maxRounds" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "LivePk" ADD COLUMN IF NOT EXISTS "currentRound" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "LivePk" ADD COLUMN IF NOT EXISTS "challengerWins" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LivePk" ADD COLUMN IF NOT EXISTS "opponentWins" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS "LiveGame" (
    "id" TEXT NOT NULL,
    "liveId" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'DRAW_GUESS',
    "status" TEXT NOT NULL DEFAULT 'LOBBY',
    "hostId" TEXT NOT NULL,
    "drawerId" TEXT,
    "word" TEXT,
    "wordHint" TEXT,
    "round" INTEGER NOT NULL DEFAULT 1,
    "maxRounds" INTEGER NOT NULL DEFAULT 3,
    "scores" JSONB NOT NULL DEFAULT '{}',
    "strokes" JSONB NOT NULL DEFAULT '[]',
    "endedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "LiveGame_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "LiveGame_liveId_status_idx" ON "LiveGame"("liveId", "status");
ALTER TABLE "LiveGame" DROP CONSTRAINT IF EXISTS "LiveGame_liveId_fkey";
ALTER TABLE "LiveGame" ADD CONSTRAINT "LiveGame_liveId_fkey" FOREIGN KEY ("liveId") REFERENCES "LiveSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;
