import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import { ConfigService } from '@nestjs/config'; import { PrismaService } from '../prisma/prisma.service'; import { SubmitPaymentDto } from './payments.dto';
@Injectable() export class PaymentsService {
 constructor(private db:PrismaService,private config:ConfigService){}
 instructions(){return {currency:'BDT',gateways:[{gateway:'BKASH',receiverNumber:this.config.get('BKASH_RECEIVER_NUMBER'),steps:['Open bKash app','Choose Send Money','Send exact amount','Copy transaction ID']},{gateway:'NAGAD',receiverNumber:this.config.get('NAGAD_RECEIVER_NUMBER'),steps:['Open Nagad app','Choose Send Money','Send exact amount','Copy transaction ID']}],notice:'Balance is credited only after manual verification.'}}
 async submit(userId:string,d:SubmitPaymentDto){const receiver=this.config.get(`${d.gateway}_RECEIVER_NUMBER`);if(!receiver)throw new BadRequestException('Gateway is unavailable');try{return await this.db.payment.create({data:{userId,gateway:d.gateway,receiverNumber:receiver,senderNumber:d.senderNumber,amount:d.amount,transactionId:d.transactionId.trim().toUpperCase()}})}catch{throw new ConflictException('This transaction ID was already submitted')}}
 listMine(userId:string){return this.db.payment.findMany({where:{userId},orderBy:{createdAt:'desc'}})}
 listPending(){return this.db.payment.findMany({where:{status:{in:['SUBMITTED','UNDER_REVIEW']}},include:{user:{select:{phone:true,profile:true}}},orderBy:{createdAt:'asc'}})}
 async approve(id:string,reviewer:string){return this.db.$transaction(async tx=>{const payment=await tx.payment.findUnique({where:{id}});if(!payment)throw new NotFoundException();if(!['SUBMITTED','UNDER_REVIEW'].includes(payment.status))throw new ConflictException('Payment already processed');const wallet=await tx.wallet.findUniqueOrThrow({where:{userId:payment.userId}});const updated=await tx.wallet.update({where:{id:wallet.id},data:{purchased:{increment:payment.amount},version:{increment:1}}});await tx.walletLedger.create({data:{walletId:wallet.id,userId:payment.userId,type:'DEPOSIT',direction:'CREDIT',amount:payment.amount,balanceBefore:wallet.purchased,balanceAfter:updated.purchased,referenceType:'PAYMENT',referenceId:payment.id,description:`Verified ${payment.gateway} deposit`,idempotencyKey:`payment:${payment.id}:approve`}});return tx.payment.update({where:{id},data:{status:'APPROVED',reviewedBy:reviewer,reviewedAt:new Date()}})},{isolationLevel:'Serializable'})}
 async reject(id:string,reviewer:string,reason:string){const p=await this.db.payment.findUnique({where:{id}});if(!p)throw new NotFoundException();if(!['SUBMITTED','UNDER_REVIEW'].includes(p.status))throw new ConflictException('Payment already processed');return this.db.payment.update({where:{id},data:{status:'REJECTED',rejectionReason:reason,reviewedBy:reviewer,reviewedAt:new Date()}})}
}
