import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createHmac, randomUUID } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { WalletService } from '../wallet/wallet.service';
import { RequestCallDto } from './calls.dto';
@Injectable() export class CallsService {
 constructor(private db:PrismaService,private wallets:WalletService,private config:ConfigService){}
 async request(callerId:string,d:RequestCallDto){return this.wallets.transaction(async tx=>{const scopedKey=`${callerId}:${d.idempotencyKey}`,prior=await tx.callSession.findUnique({where:{idempotencyKey:scopedKey}});if(prior)return prior;const vendor=await tx.vendorProfile.findUnique({where:{id:d.vendorId},include:{user:true}});if(!vendor||vendor.status!=='APPROVED')throw new NotFoundException('Vendor not found');if(!vendor.availableForCall)throw new ConflictException('Vendor is unavailable');if(vendor.userId===callerId)throw new ForbiddenException('Self calling is prohibited');const blocked=await tx.block.findFirst({where:{OR:[{blockerId:callerId,blockedUserId:vendor.userId},{blockerId:vendor.userId,blockedUserId:callerId}]}});if(blocked)throw new ForbiddenException('Calling is blocked');const gift=await tx.userGiftCard.findFirst({where:{recipientId:callerId,activatedAt:{not:null},status:{in:['ACTIVE','PARTIALLY_USED']},expiresAt:{gt:new Date()},remainingVoiceSeconds:{gte:d.maximumSeconds},OR:[{vendorId:null},{vendorId:vendor.id}]},orderBy:{expiresAt:'asc'}}),prepaid=gift?null:await tx.userPackage.findFirst({where:{userId:callerId,active:true,expiresAt:{gt:new Date()},remainingVoiceSeconds:{gte:d.maximumSeconds}},orderBy:{expiresAt:'asc'}}),sourceType=gift?'GIFT_CARD':prepaid?'PACKAGE':'WALLET',sourceId=gift?.id??prepaid?.id,reserve=sourceId?0:Math.ceil(d.maximumSeconds/60)*vendor.voiceRatePerMinute;const call=await tx.callSession.create({data:{callerId,vendorId:vendor.id,ratePerMinute:vendor.voiceRatePerMinute,reservedAmount:reserve,prepaidSeconds:sourceId?d.maximumSeconds:0,paymentSourceType:sourceType,paymentSourceId:sourceId,idempotencyKey:scopedKey}});if(reserve>0)await this.wallets.reserve(tx,callerId,reserve,call.id);await tx.notification.create({data:{userId:vendor.userId,type:'INCOMING_CALL',title:'Incoming voice call',body:'A user is requesting a voice call',data:{callId:call.id}}});return call})}
 async accept(id:string,userId:string){const call=await this.ownedVendorCall(id,userId);if(call.status!=='REQUESTED')throw new ConflictException('Call is no longer requestable');const updated=await this.db.callSession.update({where:{id},data:{status:'ACCEPTED'}});return{...updated,rtc:this.rtcToken(id,userId),channelName:`call_${id}`}}
 async reject(id:string,userId:string){const call=await this.ownedVendorCall(id,userId);if(call.status!=='REQUESTED')throw new ConflictException('Call can no longer be rejected');return this.release(id,'REJECTED')}
 async cancel(id:string,userId:string){const call=await this.db.callSession.findUnique({where:{id}});if(!call||call.callerId!==userId)throw new ForbiddenException();if(!['REQUESTED','ACCEPTED','CONNECTING'].includes(call.status))throw new ConflictException('Call can no longer be cancelled');return this.release(id,'CANCELLED')}
 async joinToken(id:string,userId:string){const c=await this.db.callSession.findUnique({where:{id},include:{vendor:true}});if(!c||![c.callerId,c.vendor.userId].includes(userId))throw new ForbiddenException();if(!['ACCEPTED','CONNECTING','ACTIVE'].includes(c.status))throw new ConflictException('Call cannot be joined');return{token:this.rtcToken(id,userId),channelName:`call_${id}`,expiresInSeconds:600}}
 async connected(id:string,userId:string){const call=await this.assertParticipant(id,userId);if(!['ACCEPTED','CONNECTING','ACTIVE'].includes(call.status))throw new ConflictException('Call cannot connect');if(call.connectedAt)return call;return this.db.callSession.update({where:{id},data:{status:'ACTIVE',connectedAt:new Date()}})}
 async heartbeat(id:string,userId:string,seconds:number){const c=await this.assertParticipant(id,userId);if(c.status!=='ACTIVE')throw new ConflictException('Call is not active');const max=c.prepaidSeconds||Math.floor(c.reservedAmount/c.ratePerMinute*60);return{remainingSeconds:Math.max(0,max-seconds),mustEnd:seconds>=max}}
 async end(id:string,userId:string,_reportedSeconds?:number){await this.assertParticipant(id,userId);return this.wallets.transaction(async tx=>{const c=await tx.callSession.findUniqueOrThrow({where:{id},include:{vendor:{include:{user:true}}}});if(['COMPLETED','REJECTED','CANCELLED'].includes(c.status))return c;const duration=c.connectedAt?Math.max(0,Math.floor((Date.now()-c.connectedAt.getTime())/1000)):0,maxSeconds=c.prepaidSeconds||Math.floor(c.reservedAmount/c.ratePerMinute*60),billed=Math.min(duration,maxSeconds),gross=Math.ceil(billed*c.ratePerMinute/60),vendorAmount=Math.floor(gross*c.vendor.commissionPercent/100),platformAmount=gross-vendorAmount;if(c.reservedAmount>0)await this.wallets.settleReservation(tx,c.callerId,c.reservedAmount,Math.min(c.reservedAmount,gross),c.id);if(c.paymentSourceType==='PACKAGE'&&c.paymentSourceId&&billed>0)await tx.userPackage.update({where:{id:c.paymentSourceId},data:{remainingVoiceSeconds:{decrement:billed}}});if(c.paymentSourceType==='GIFT_CARD'&&c.paymentSourceId&&billed>0){const gift=await tx.userGiftCard.findUniqueOrThrow({where:{id:c.paymentSourceId}}),remaining=gift.remainingVoiceSeconds-billed;await tx.userGiftCard.update({where:{id:gift.id},data:{remainingVoiceSeconds:remaining,status:remaining===0&&gift.remainingMessages===0?'FULLY_USED':'PARTIALLY_USED'}})}if(vendorAmount>0){await this.wallets.creditPendingEarning(tx,c.vendor.userId,vendorAmount,c.id);await tx.earning.create({data:{vendorId:c.vendorId,callId:c.id,sourceType:'VOICE_CALL',sourceId:c.id,grossAmount:gross,vendorAmount,platformAmount,availableAt:new Date(Date.now()+7*86400000)}})}return tx.callSession.update({where:{id},data:{status:'COMPLETED',endedAt:new Date(),durationSeconds:duration,billedSeconds:billed,grossAmount:gross,vendorAmount,platformAmount}})})}
 history(userId:string){return this.db.callSession.findMany({where:{OR:[{callerId:userId},{vendor:{userId}}]},include:{vendor:{include:{user:{select:{profile:true}}}}},orderBy:{createdAt:'desc'},take:100})}
 private async ownedVendorCall(id:string,userId:string){const c=await this.db.callSession.findUnique({where:{id},include:{vendor:true}});if(!c||c.vendor.userId!==userId)throw new ForbiddenException();return c}
 private async assertParticipant(id:string,userId:string){const c=await this.db.callSession.findUnique({where:{id},include:{vendor:true}});if(!c||![c.callerId,c.vendor.userId].includes(userId))throw new ForbiddenException();return c}
 private release(id:string,status:'REJECTED'|'CANCELLED'){return this.wallets.transaction(async tx=>{const call=await tx.callSession.findUniqueOrThrow({where:{id}});if(call.reservedAmount>0)await this.wallets.settleReservation(tx,call.callerId,call.reservedAmount,0,call.id);return tx.callSession.update({where:{id},data:{status,endedAt:new Date()}})})}
 private rtcToken(callId:string,userId:string){const secret=this.config.get('AGORA_APP_CERTIFICATE')??'development-only';return createHmac('sha256',secret).update(`${callId}:${userId}:${Math.floor(Date.now()/1000)+600}:${randomUUID()}`).digest('hex')}
}
