import { BadGatewayException, Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createHmac, randomUUID } from 'crypto';

@Injectable()
export class SmsService {
  private readonly logger=new Logger(SmsService.name);
  constructor(private readonly config:ConfigService){}
  async sendOtp(phone:string,code:string,expiresMinutes:number){const provider=(this.config.get<string>('SMS_PROVIDER')??'development').toLowerCase();if(provider==='development')return{provider,accepted:true};const to=this.normalize(phone);const message=`Your SocialConnect verification code is ${code}. It expires in ${expiresMinutes} minutes. Never share this code.`;if(provider==='twilio')return this.twilio(to,message);if(provider==='webhook')return this.webhook(to,message);throw new BadGatewayException('SMS provider is not configured')}
  async sendTransactional(phone:string,message:string){const provider=(this.config.get<string>('SMS_PROVIDER')??'development').toLowerCase();if(provider==='development')return{provider,accepted:true};const to=this.normalize(phone);if(provider==='twilio')return this.twilio(to,message);if(provider==='webhook')return this.webhook(to,message);throw new BadGatewayException('SMS provider is not configured')}
  normalize(phone:string){if(phone.startsWith('+'))return phone;const country=this.config.get<string>('SMS_DEFAULT_COUNTRY_CODE')??'+880';return phone.startsWith('0')?`${country}${phone.slice(1)}`:`${country}${phone}`}
  private async twilio(to:string,body:string){const sid=this.config.getOrThrow<string>('TWILIO_ACCOUNT_SID'),token=this.config.getOrThrow<string>('TWILIO_AUTH_TOKEN'),from=this.config.getOrThrow<string>('TWILIO_FROM_NUMBER');const form=new URLSearchParams({To:to,From:from,Body:body});const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(sid)}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${sid}:${token}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:form});if(!response.ok){this.logger.error(`Twilio rejected SMS with status ${response.status}`);throw new BadGatewayException('SMS delivery failed')}const result=await response.json() as {sid?:string};return{provider:'twilio',accepted:true,providerId:result.sid}}
  private async webhook(to:string,message:string){const url=this.config.getOrThrow<string>('SMS_WEBHOOK_URL'),secret=this.config.getOrThrow<string>('SMS_WEBHOOK_SECRET'),id=randomUUID(),timestamp=Date.now().toString(),payload=JSON.stringify({id,to,message,timestamp});const signature=createHmac('sha256',secret).update(payload).digest('hex');const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-SocialConnect-Signature':signature,'X-SocialConnect-Timestamp':timestamp},body:payload});if(!response.ok){this.logger.error(`SMS webhook rejected request with status ${response.status}`);throw new BadGatewayException('SMS delivery failed')}return{provider:'webhook',accepted:true,providerId:id}}
}
