import React, { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { api } from '../api/client';
import { realtime } from '../api/realtime';
import { Avatar, Button, Card, EmptyState, Pill, Screen, Title } from '../components/UI';
import { colors, radius, spacing } from '../theme';

export function CallsScreen() {
  const [calls, setCalls] = useState<any[]>([]); const [me, setMe] = useState<any>(); const [loading, setLoading] = useState(false); const navigation = useNavigation<any>();
  const load = useCallback(() => { setLoading(true); return Promise.all([api.get('/calls/history'), api.get('/users/me')]).then(([history, user]) => { setCalls(history.data); setMe(user.data); }).finally(() => setLoading(false)); }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  useEffect(() => { let client: any; const refresh = () => void load(); void realtime().then(value => { client = value; for (const event of ['call:accepted', 'call:rejected', 'call:cancelled', 'call:connected', 'call:ended']) client?.on(event, refresh); }); return () => { for (const event of ['call:accepted', 'call:rejected', 'call:cancelled', 'call:connected', 'call:ended']) client?.off(event, refresh); }; }, [load]);
  const act = async (item: any, action: 'accept' | 'reject' | 'cancel') => { try { await api.post(`/calls/${item.id}/${action}`); if (action === 'accept') navigation.navigate('ActiveCall', { callId: item.id, title: 'Voice call' }); else void load(); } catch (error: any) { Alert.alert('Could not update call', error.response?.data?.message ?? 'Try again'); } };
  return <Screen padded={false}><FlatList contentContainerStyle={styles.list} data={calls} keyExtractor={item => item.id} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={colors.primary} />} ListHeaderComponent={<Title subtitle="Secure, private and billed by the server">Calls</Title>} ListEmptyComponent={!loading ? <EmptyState icon="◉" title="No calls yet" body="Open a creator profile to request your first voice conversation." /> : null} renderItem={({ item }) => { const isVendor = item.vendor?.userId === me?.id; const active = ['ACCEPTED', 'CONNECTING', 'ACTIVE'].includes(item.status); const name = item.vendor?.user?.profile?.displayName ?? 'Voice conversation'; const completed = item.status === 'COMPLETED'; return <Card><View style={styles.row}><Avatar name={name} size={50} online={active} /><View style={styles.info}><Text style={styles.name}>{name}</Text><Text style={styles.meta}>{new Date(item.createdAt).toLocaleString()}</Text></View><Pill label={item.status.replaceAll('_', ' ')} tone={completed ? 'success' : active ? 'primary' : 'neutral'} /></View>{completed ? <View style={styles.summary}><View><Text style={styles.value}>{Math.ceil((item.billedSeconds ?? 0) / 60)} min</Text><Text style={styles.label}>Billed time</Text></View><View><Text style={styles.value}>{item.grossAmount ?? 0} pts</Text><Text style={styles.label}>Final charge</Text></View></View> : null}{item.status === 'REQUESTED' ? isVendor ? <View style={styles.actions}><View style={styles.flex}><Button title="Decline" variant="ghost" onPress={() => act(item, 'reject')} /></View><View style={styles.flex}><Button title="Accept" onPress={() => act(item, 'accept')} /></View></View> : <Button title="Cancel request" variant="ghost" onPress={() => act(item, 'cancel')} /> : null}{active ? <Button title={item.status === 'ACTIVE' ? 'Return to call' : 'Join voice call'} icon="◉" onPress={() => navigation.navigate('ActiveCall', { callId: item.id, title: name })} /> : null}</Card>; }} /></Screen>;
}
const styles = StyleSheet.create({ list: { padding: spacing.xl, paddingBottom: 110 }, row: { flexDirection: 'row', alignItems: 'center' }, info: { flex: 1, marginLeft: 12 }, name: { color: colors.text, fontSize: 16, fontWeight: '850' as any }, meta: { color: colors.muted, fontSize: 10, marginTop: 4 }, summary: { flexDirection: 'row', justifyContent: 'space-around', borderTopWidth: 1, borderTopColor: colors.border, marginTop: 15, paddingTop: 14 }, value: { color: colors.text, fontWeight: '900', textAlign: 'center' }, label: { color: colors.muted, fontSize: 10, marginTop: 3 }, actions: { flexDirection: 'row', gap: 10, marginTop: 8 }, flex: { flex: 1 } });
