// @ts-nocheck
import React, { useCallback, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { api } from '../api/client';
import { Avatar, Card, EmptyState, Eyebrow, Pill, Screen, SectionTitle, Title } from '../components/UI';
import { colors, radius, spacing } from '../theme';

export function HomeScreen() {
  const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(false); const navigation = useNavigation<any>();
  const load = useCallback(() => { setLoading(true); api.get('/vendors/discover').then(response => setData(response.data)).finally(() => setLoading(false)); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  return <Screen padded={false}>
    <FlatList contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={colors.primary} />} data={data} keyExtractor={item => item.id} ListHeaderComponent={<>
      <View style={styles.topRow}><View><Eyebrow>SocialConnect</Eyebrow><Title subtitle="Meet verified creators who match your vibe">Discover</Title></View><Pressable style={styles.bell} onPress={() => navigation.navigate('Notifications')}><Text style={styles.bellText}>♢</Text></Pressable></View>
      <Pressable style={styles.search} onPress={() => navigation.navigate('Search')}><Text style={styles.searchIcon}>⌕</Text><Text style={styles.searchText}>Search people, language or interests</Text></Pressable>
      <View style={styles.quickRow}><Pressable style={styles.quickCard} onPress={() => navigation.navigate('Connections')}><Text style={styles.quickIcon}>◎</Text><Text style={styles.quickTitle}>Connections</Text><Text style={styles.quickBody}>People waiting</Text></Pressable><Pressable style={[styles.quickCard, styles.quickPurple]} onPress={() => navigation.navigate('Packages')}><Text style={styles.quickIcon}>✦</Text><Text style={[styles.quickTitle, { color: '#FFF' }]}>Get more time</Text><Text style={[styles.quickBody, { color: '#DCD3FF' }]}>Explore packages</Text></Pressable></View>
      <Pressable style={styles.supportLink} onPress={() => navigation.navigate('Support')}><Text style={styles.supportIcon}>♡</Text><View style={{flex:1}}><Text style={styles.supportTitle}>Need a hand?</Text><Text style={styles.supportBody}>Private account, payment and safety support</Text></View><Text style={styles.chevron}>›</Text></Pressable>
      <SectionTitle action="See all" onAction={() => navigation.navigate('Search')}>Creators for you</SectionTitle>
    </>}
    ListEmptyComponent={!loading ? <EmptyState icon="✦" title="Fresh connections are coming" body="No approved creators are available yet. Pull to refresh in a moment." /> : null}
    renderItem={({ item }) => { const profile = item.user.profile; return <Pressable onPress={() => navigation.navigate('Vendor', { vendor: item })}><Card style={styles.creatorCard}><View style={styles.creatorRow}><Avatar name={profile.displayName} size={58} online={item.availableForCall} /><View style={styles.creatorInfo}><View style={styles.nameRow}><Text style={styles.creatorName}>{profile.displayName}</Text>{profile.isVerified ? <Text style={styles.verified}>✓</Text> : null}</View><Text style={styles.handle}>@{profile.username} · {profile.country}</Text><View style={styles.pills}><Pill label={item.availableForCall ? 'Online now' : 'Offline'} tone={item.availableForCall ? 'success' : 'neutral'} /><Pill label={`★ ${Number(item.averageRating || 0).toFixed(1)}`} tone="gold" /></View></View><Text style={styles.chevron}>›</Text></View><View style={styles.priceRow}><Text style={styles.price}>{item.voiceRatePerMinute} pts<Text style={styles.priceUnit}> / min</Text></Text><Text style={styles.chatPrice}>{item.paidChatRate} pts / message</Text></View></Card></Pressable>; }} />
  </Screen>;
}
const styles = StyleSheet.create({ list: { padding: spacing.xl, paddingBottom: 120 }, topRow: { flexDirection: 'row', justifyContent: 'space-between' }, bell: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border }, bellText: { fontSize: 24, color: colors.text }, search: { height: 54, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.lg, marginBottom: spacing.lg }, searchIcon: { fontSize: 24, color: colors.primary, marginRight: 10 }, searchText: { color: colors.muted, fontSize: 14 }, quickRow: { flexDirection: 'row', gap: 12 }, quickCard: { flex: 1, minHeight: 116, backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.lg, borderWidth: 1, borderColor: colors.border }, quickPurple: { backgroundColor: colors.dark, borderColor: colors.dark }, quickIcon: { color: colors.primary, fontSize: 22, marginBottom: 12 }, quickTitle: { color: colors.text, fontWeight: '850', fontSize: 15 }, quickBody: { color: colors.muted, marginTop: 3, fontSize: 12 },supportLink:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:14,marginTop:12},supportIcon:{color:colors.primary,fontSize:22},supportTitle:{color:colors.text,fontWeight:'850'},supportBody:{color:colors.muted,fontSize:11,marginTop:2}, creatorCard: { padding: 15 }, creatorRow: { flexDirection: 'row', alignItems: 'center' }, creatorInfo: { flex: 1, marginLeft: 12 }, nameRow: { flexDirection: 'row', alignItems: 'center' }, creatorName: { color: colors.text, fontSize: 17, fontWeight: '850' }, verified: { color: '#FFF', backgroundColor: colors.primary, overflow: 'hidden', width: 17, height: 17, borderRadius: 9, textAlign: 'center', fontSize: 11, marginLeft: 5 }, handle: { color: colors.muted, fontSize: 12, marginTop: 3 }, pills: { flexDirection: 'row', gap: 6, marginTop: 9 }, chevron: { color: colors.muted, fontSize: 30 }, priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: colors.border, marginTop: 14, paddingTop: 12 }, price: { color: colors.primary, fontWeight: '900', fontSize: 15 }, priceUnit: { color: colors.muted, fontWeight: '600', fontSize: 12 }, chatPrice: { color: colors.textSoft, fontSize: 12, fontWeight: '700' } });
