import React, { useEffect, useState } from 'react';
import { Alert, FlatList, StyleSheet, Text, View } from 'react-native';
import { api } from '../api/client';
import { Button, Card, Eyebrow, Pill, Screen, Title } from '../components/UI';
import { colors, spacing } from '../theme';
export function MembershipsScreen() {
  const [plans,setPlans]=useState<any[]>([]),[mine,setMine]=useState<any[]>([]),[busy,setBusy]=useState('');
  const load=()=>Promise.all([api.get('/memberships'),api.get('/memberships/mine')]).then(([p,m])=>{setPlans(p.data);setMine(m.data)});useEffect(()=>{void load()},[]);
  const subscribe=async(plan:any)=>{try{setBusy(plan.id);await api.post(`/memberships/${plan.id}/subscribe`,{idempotencyKey:`mobile-${Date.now()}-${Math.random()}`});Alert.alert('Membership active',`${plan.name} benefits are ready to use.`);await load()}catch(error:any){Alert.alert('Could not subscribe',error.response?.data?.message??'Try again')}finally{setBusy('')}};
  const current=mine.find(item=>item.status==='ACTIVE'&&new Date(item.expiresAt)>new Date());
  return <Screen padded={false}><FlatList contentContainerStyle={styles.list} data={plans} keyExtractor={item=>item.id} ListHeaderComponent={<><Eyebrow>More value every month</Eyebrow><Title subtitle="Lower call rates, monthly bonus points and member-only benefits">Memberships</Title>{current?<Card style={styles.current}><Pill label="CURRENT MEMBERSHIP" tone="success"/><Text style={styles.currentName}>{current.plan.name}</Text><Text style={styles.currentBody}>Benefits renew until {new Date(current.expiresAt).toLocaleDateString()}</Text></Card>:null}</>} renderItem={({item,index})=>{const benefits=item.benefits??{},active=current?.planId===item.id;return <Card style={index===1?styles.featured:undefined}><View style={styles.planTop}><View><Text style={[styles.planName,index===1&&styles.light]}>{item.name}</Text><Text style={[styles.price,index===1&&styles.light]}>{item.price} pts <Text style={styles.period}>/ {item.durationDays} days</Text></Text></View>{item.badge?<Pill label={item.badge} tone={index===1?'gold':'primary'}/>:null}</View><Text style={[styles.description,index===1&&styles.featuredMuted]}>{item.description}</Text><View style={styles.benefits}>{(benefits.callDiscountPercent||benefits.voiceDiscountPercent)?<Text style={[styles.benefit,index===1&&styles.light]}>✓ Up to {benefits.callDiscountPercent??benefits.voiceDiscountPercent}% lower call rates</Text>:null}{benefits.bonusPoints?<Text style={[styles.benefit,index===1&&styles.light]}>✓ {benefits.bonusPoints} monthly bonus points</Text>:null}{benefits.prioritySupport?<Text style={[styles.benefit,index===1&&styles.light]}>✓ Priority support</Text>:null}{benefits.priorityCallQueue?<Text style={[styles.benefit,index===1&&styles.light]}>✓ Priority call queue</Text>:null}</View><Button title={active?'Current plan':`Choose ${item.name}`} variant={index===1?'secondary':'primary'} disabled={active} loading={busy===item.id} onPress={()=>subscribe(item)}/></Card>}}/></Screen>;
}
const styles=StyleSheet.create({list:{padding:spacing.xl,paddingBottom:80},current:{backgroundColor:colors.successSoft,borderColor:'#C7EFDF'},currentName:{color:colors.text,fontSize:20,fontWeight:'900',marginTop:13},currentBody:{color:colors.textSoft,marginTop:5},featured:{backgroundColor:colors.dark,borderColor:colors.dark},planTop:{flexDirection:'row',justifyContent:'space-between'},planName:{color:colors.text,fontSize:22,fontWeight:'900'},price:{color:colors.primary,fontSize:19,fontWeight:'900',marginTop:6},period:{fontSize:11,color:colors.muted},light:{color:'#FFF'},description:{color:colors.muted,lineHeight:20,marginTop:14},featuredMuted:{color:'#C9C2DD'},benefits:{gap:9,marginVertical:18},benefit:{color:colors.textSoft,fontSize:12}});
