import React, { useCallback, useEffect, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { api } from '../api/client';
import { realtime } from '../api/realtime';
import { EmptyState, Pill, Screen, Title } from '../components/UI';
import { colors, radius, spacing } from '../theme';
const icons: Record<string, string> = { INCOMING_CALL: '◉', MESSAGE: '✉', GIFT: '♥', GIFT_CARD: '◇', WITHDRAWAL: '↗', REVIEW: '★', VENDOR_REVIEW: '✓', FOLLOW: '●', CONNECTION_REQUEST: '◎' };
export function NotificationsScreen() {
  const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(false);
  const load = useCallback(() => { setLoading(true); return api.get('/notifications').then(response => setData(response.data)).finally(() => setLoading(false)); }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  useEffect(() => { let client: any; const handler = (item: any) => setData(current => current.some(existing => existing.id === item.id) ? current : [item, ...current]); void realtime().then(value => { client = value; client?.on('notification:new', handler); }); return () => client?.off('notification:new', handler); }, []);
  const mark = async (id: string) => { await api.patch(`/notifications/${id}/read`); setData(current => current.map(item => item.id === id ? { ...item, readAt: new Date().toISOString() } : item)); };
  return <Screen padded={false}><FlatList contentContainerStyle={styles.list} data={data} keyExtractor={item => item.id} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={colors.primary} />} ListHeaderComponent={<View style={styles.header}><Title subtitle="Calls, conversations, gifts and account updates">Notifications</Title>{data.some(item => !item.readAt) ? <Pressable onPress={() => api.patch('/notifications/read-all').then(load)}><Text style={styles.readAll}>Mark all read</Text></Pressable> : null}</View>} ListEmptyComponent={!loading ? <EmptyState icon="♢" title="You’re all caught up" body="New calls, messages, gifts and account updates will appear here." /> : null} renderItem={({ item }) => <Pressable onPress={() => mark(item.id)} style={[styles.item, !item.readAt && styles.unread]}><View style={[styles.icon, !item.readAt && styles.unreadIcon]}><Text style={styles.iconText}>{icons[item.type] ?? '•'}</Text></View><View style={styles.info}><Text style={[styles.itemTitle, !item.readAt && { fontWeight: '900' }]}>{item.title}</Text><Text style={styles.body}>{item.body}</Text><Text style={styles.time}>{new Date(item.createdAt).toLocaleString()}</Text></View>{!item.readAt ? <View style={styles.dot} /> : null}</Pressable>} /></Screen>;
}
const styles = StyleSheet.create({ list: { padding: spacing.xl, paddingBottom: 80 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, readAll: { color: colors.primary, fontWeight: '800', fontSize: 12, marginTop: 8 }, item: { flexDirection: 'row', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: 14, marginBottom: 10 }, unread: { borderColor: colors.primary, backgroundColor: colors.primaryLight }, icon: { width: 44, height: 44, borderRadius: 15, backgroundColor: colors.surfaceSoft, alignItems: 'center', justifyContent: 'center' }, unreadIcon: { backgroundColor: colors.primaryLight }, iconText: { color: colors.primary, fontWeight: '900', fontSize: 18 }, info: { flex: 1, marginLeft: 12 }, itemTitle: { color: colors.text, fontWeight: '700' }, body: { color: colors.textSoft, fontSize: 12, lineHeight: 18, marginTop: 4 }, time: { color: colors.muted, fontSize: 10, marginTop: 7 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary, marginTop: 4 } });
