import React,{useState}from'react';
import{Alert,FlatList,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{useNavigation}from'@react-navigation/native';
import{api,apiErrorMessage}from'../api/client';
import{Avatar,Button,Card,EmptyState,Eyebrow,Field,Pill,Screen,Title}from'../components/UI';
import{colors,radius,spacing}from'../theme';

export function SearchScreen(){
  const navigation=useNavigation<any>();const[query,setQuery]=useState(''),[language,setLanguage]=useState(''),[interest,setInterest]=useState(''),[maxRate,setMaxRate]=useState('');const[users,setUsers]=useState<any[]>([]),[loading,setLoading]=useState(false),[vendorOnly,setVendorOnly]=useState(true),[onlineOnly,setOnlineOnly]=useState(false),[searched,setSearched]=useState(false);
  const search=async()=>{try{setLoading(true);const{data}=await api.get('/social/discover',{params:{query:query||undefined,language:language||undefined,interest:interest||undefined,maxRate:maxRate?Number(maxRate):undefined,vendor:vendorOnly?'true':undefined,online:onlineOnly?'true':undefined,limit:50}});setUsers(data);setSearched(true)}catch(error:any){Alert.alert('Search failed',apiErrorMessage(error, 'Try again'))}finally{setLoading(false)}};
  const action=async(path:string)=>{try{await api.post(path);void search()}catch(error:any){Alert.alert('Action failed',apiErrorMessage(error, 'Try again'))}};
  return <Screen padded={false}><FlatList data={users} keyExtractor={item=>item.id} contentContainerStyle={styles.list} ListHeaderComponent={<><Eyebrow>CURATED DISCOVERY</Eyebrow><Title subtitle="Find people by language, interests, availability and price">Find your people</Title><Field placeholder="Name or @username" value={query} onChangeText={setQuery}/><View style={styles.row}><Field style={styles.flex} placeholder="Language" value={language} onChangeText={setLanguage}/><Field style={styles.flex} placeholder="Interest" value={interest} onChangeText={setInterest}/></View><Field placeholder="Maximum voice points / minute" keyboardType="number-pad" value={maxRate} onChangeText={setMaxRate}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><Filter label="Verified creators" active={vendorOnly} onPress={()=>setVendorOnly(value=>!value)}/><Filter label="Online now" active={onlineOnly} onPress={()=>setOnlineOnly(value=>!value)}/></ScrollView><Button title={loading?'Searching…':'Discover matches'} icon="⌕" disabled={loading} onPress={search}/><Text style={styles.results}>{searched?`${users.length} privacy-safe matches`:'Search respects every member’s visibility settings'}</Text></>}
  renderItem={({item})=>{const vendor=item.vendor,profile=item.profile;return <Pressable disabled={!vendor} onPress={()=>vendor&&navigation.navigate('Vendor',{vendor:{...vendor,user:{profile}}})}><Card style={styles.person}><View style={styles.personRow}><Avatar name={profile?.displayName} size={54} online={profile?.online}/><View style={styles.info}><View style={styles.nameRow}><Text style={styles.name}>{profile?.displayName}</Text>{profile?.isVerified?<Text style={styles.verified}>✓</Text>:null}</View><Text style={styles.meta}>@{profile?.username}{profile?.country?` · ${profile.country}`:''}</Text><View style={styles.pills}>{vendor?<Pill label={`★ ${Number(vendor.averageRating??0).toFixed(1)}`} tone="gold"/>:null}{vendor?<Pill label={`${vendor.voiceRatePerMinute} pts/min`} tone="primary"/>:null}</View></View><Text style={styles.chevron}>{vendor?'›':''}</Text></View><View style={styles.actions}><Button title={item.followers?.length?'Following':'Follow'} variant="secondary" disabled={!!item.followers?.length} onPress={()=>action(`/social/follow/${item.id}`)}/><Button title="Connect" variant="ghost" onPress={()=>action(`/social/connections/${item.id}`)}/></View></Card></Pressable>}}
  ListEmptyComponent={searched&&!loading?<EmptyState icon="⌕" title="No matches yet" body="Try removing a filter or searching another language or interest."/>:null}/></Screen>;
}
function Filter({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,active&&styles.chipActive]}><Text style={[styles.chipText,active&&styles.chipTextActive]}>{active?'✓ ':''}{label}</Text></Pressable>}
const styles=StyleSheet.create({list:{padding:spacing.xl,paddingBottom:110},row:{flexDirection:'row',gap:10},flex:{flex:1},chips:{gap:8,paddingBottom:spacing.md},chip:{paddingHorizontal:16,paddingVertical:11,borderRadius:999,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},chipActive:{backgroundColor:colors.primaryMuted,borderColor:colors.primary},chipText:{color:colors.muted,fontWeight:'700',fontSize:13},chipTextActive:{color:colors.primaryDark},results:{color:colors.muted,fontSize:12,marginVertical:spacing.lg},person:{padding:16},personRow:{flexDirection:'row',alignItems:'center'},info:{flex:1,marginLeft:12},nameRow:{flexDirection:'row',alignItems:'center'},name:{color:colors.text,fontWeight:'800',fontSize:16,letterSpacing:-0.2},verified:{color:'#FFF',backgroundColor:colors.primary,width:17,height:17,borderRadius:9,textAlign:'center',fontSize:11,marginLeft:5,overflow:'hidden'},meta:{color:colors.muted,fontSize:12,marginTop:3},pills:{flexDirection:'row',gap:5,marginTop:8},chevron:{color:colors.muted,fontSize:26,opacity:0.4},actions:{borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.border,marginTop:14,paddingTop:12,flexDirection:'row',gap:8},});
