import React,{useCallback,useState}from'react';
import{Alert,StyleSheet,Text,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{api}from'../api/client';
import{Button,Card,EmptyState,Eyebrow,Pill,Screen,Title}from'../components/UI';
import{useAuth}from'../store/auth';
import{colors}from'../theme';
export function SecurityActivityScreen(){const[events,setEvents]=useState<any[]>([]),logout=useAuth(state=>state.logout),load=useCallback(()=>api.get('/auth/security-activity').then(response=>setEvents(response.data)),[]);useFocusEffect(useCallback(()=>{void load()},[load]));const all=()=>Alert.alert('Sign out every device','This revokes every mobile and web session, including this one.',[{text:'Cancel',style:'cancel'},{text:'Sign out all',style:'destructive',onPress:async()=>{await api.post('/auth/logout-all');await logout()}}]);return <Screen scroll><Eyebrow>ACCOUNT SECURITY</Eyebrow><Title subtitle="Review successful and blocked access attempts">Security activity</Title><Card><Text style={styles.title}>See something unfamiliar?</Text><Text style={styles.body}>Change your password and revoke every session. SocialConnect never asks for your OTP or password.</Text><Button title="Sign out all devices" variant="danger" onPress={all}/></Card>{events.length?events.map(item=><Card key={item.id}><View style={styles.row}><View style={{flex:1}}><Text style={styles.event}>{item.successful?'Successful sign-in':'Blocked sign-in attempt'}</Text><Text style={styles.body}>{item.reason?.replaceAll(',',' · ').replaceAll('_',' ').toLowerCase()??'Known device'} · {new Date(item.createdAt).toLocaleString()}</Text><Text style={styles.meta}>{item.ipAddress??'Network unavailable'} · {item.deviceId??'Unknown device'}</Text></View><Pill label={item.riskLevel} tone={item.riskLevel==='LOW'?'success':item.riskLevel==='HIGH'?'gold':'neutral'}/></View></Card>):<EmptyState title="No security events" body="Recent sign-in activity will appear here."/>}</Screen>}
const styles=StyleSheet.create({row:{flexDirection:'row',gap:10},title:{color:colors.text,fontSize:17,fontWeight:'900'},event:{color:colors.text,fontWeight:'800'},body:{color:colors.textSoft,lineHeight:19,marginTop:5},meta:{color:colors.muted,fontSize:10,marginTop:7}});
