import React,{useState}from'react';
import{Alert,Platform,StyleSheet,Text}from'react-native';
import appleAuth,{AppleRequestOperation,AppleRequestScope}from'@invertase/react-native-apple-authentication';
import{GoogleSignin}from'@react-native-google-signin/google-signin';
import{api}from'../api/client';
import{Button,Card,Eyebrow,Field,Screen,Title}from'../components/UI';
import{GOOGLE_WEB_CLIENT_ID}from'../config/authProviders';
import{useAuth}from'../store/auth';
import{colors}from'../theme';

export function SocialAuthScreen({route}:{route:any}){const provider=route.params?.provider as'GOOGLE'|'APPLE';const[username,setUsername]=useState(''),[displayName,setDisplayName]=useState(''),[dateOfBirth,setDob]=useState(''),[busy,setBusy]=useState(false);const setTokens=useAuth(state=>state.setTokens);const submit=async()=>{try{setBusy(true);const{data:nonceData}=await api.post('/auth/oauth/nonce');let identityToken:string|undefined,name=displayName;if(provider==='GOOGLE'){if(!GOOGLE_WEB_CLIENT_ID)throw new Error('Google client ID is not configured in authProviders.ts');GoogleSignin.configure({webClientId:GOOGLE_WEB_CLIENT_ID});await GoogleSignin.hasPlayServices({showPlayServicesUpdateDialog:true});const response=await GoogleSignin.signIn();identityToken=response.data?.idToken??undefined;name=name||response.data?.user.name??''}else{if(Platform.OS!=='ios'||!appleAuth.isSupported)throw new Error('Sign in with Apple requires a supported Apple device');const credential=await appleAuth.performRequest({requestedOperation:AppleRequestOperation.LOGIN,requestedScopes:[AppleRequestScope.FULL_NAME,AppleRequestScope.EMAIL],nonce:nonceData.nonce});identityToken=credential.identityToken??undefined;const appleName=[credential.fullName?.givenName,credential.fullName?.familyName].filter(Boolean).join(' ');name=name||appleName}if(!identityToken)throw new Error('The provider did not return an identity token');const{data}=await api.post(`/auth/${provider.toLowerCase()}`,{identityToken,nonce:nonceData.nonce,username:username.trim(),displayName:name.trim(),dateOfBirth,termsAccepted:true,deviceName:`${Platform.OS} SocialConnect`});await setTokens(data.accessToken,data.refreshToken,data.deviceId)}catch(error:any){Alert.alert(`${provider==='GOOGLE'?'Google':'Apple'} sign-in failed`,error.response?.data?.message??error.message??'Try again')}finally{setBusy(false)}};return <Screen scroll><Eyebrow>VERIFIED SIGN-IN</Eyebrow><Title subtitle="These details are only used when creating a new SocialConnect account">Continue with {provider==='GOOGLE'?'Google':'Apple'}</Title><Card><Text style={styles.secure}>◆ Server-verified identity</Text><Text style={styles.help}>SocialConnect verifies the provider signature, audience, expiry and a one-time nonce. You must still be 18 or older.</Text></Card><Field placeholder="Choose a username" autoCapitalize="none" value={username} onChangeText={setUsername}/><Field placeholder="Display name" value={displayName} onChangeText={setDisplayName}/><Field placeholder="Date of birth (YYYY-MM-DD)" value={dateOfBirth} onChangeText={setDob}/><Text style={styles.terms}>By continuing, you confirm you are at least 18 and accept the Terms and Privacy Policy.</Text><Button title={`Continue with ${provider==='GOOGLE'?'Google':'Apple'}`} loading={busy} disabled={username.trim().length<3||displayName.trim().length<2||!/^\d{4}-\d{2}-\d{2}$/.test(dateOfBirth)} onPress={submit}/></Screen>}
const styles=StyleSheet.create({secure:{color:colors.primary,fontWeight:'900'},help:{color:colors.muted,lineHeight:20,marginTop:7},terms:{color:colors.muted,fontSize:12,lineHeight:18,marginVertical:12}});
