import React,{useCallback,useMemo,useState}from'react';
import{Alert,Pressable,StyleSheet,Text,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{api,apiErrorMessage}from'../api/client';
import{Button,Card,EmptyState,Eyebrow,Field,Pill,Screen,SectionTitle,Title}from'../components/UI';
import{colors,spacing}from'../theme';

const categories=['ACCOUNT','PAYMENT','CALL','CHAT','VENDOR','WITHDRAWAL','SAFETY','OTHER'];
export function SupportScreen(){
  const[tickets,setTickets]=useState<any[]>([]),[selectedId,setSelectedId]=useState<string>(),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[category,setCategory]=useState('ACCOUNT'),[reply,setReply]=useState(''),[busy,setBusy]=useState(false);
  const selected=useMemo(()=>tickets.find(ticket=>ticket.id===selectedId),[tickets,selectedId]);
  const load=useCallback(()=>api.get('/support').then(response=>setTickets(response.data)),[]);
  useFocusEffect(useCallback(()=>{void load()},[load]));
  const create=async()=>{try{setBusy(true);await api.post('/support',{subject,body,category});setSubject('');setBody('');Alert.alert('Request received','Our support team will reply in this secure thread.');await load()}catch(error:any){Alert.alert('Could not send',apiErrorMessage(error, 'Try again'))}finally{setBusy(false)}};
  const sendReply=async()=>{if(!selected)return;try{setBusy(true);await api.post(`/support/${selected.id}/replies`,{body:reply});setReply('');await load()}catch(error:any){Alert.alert('Could not reply',apiErrorMessage(error, 'Try again'))}finally{setBusy(false)}};
  if(selected)return <Screen scroll><Eyebrow>SECURE SUPPORT THREAD</Eyebrow><Title subtitle={`${selected.category} · opened ${new Date(selected.createdAt).toLocaleDateString()}`}>{selected.subject}</Title><Button title="Back to requests" variant="ghost" onPress={()=>setSelectedId(undefined)}/>{selected.messages.map((message:any)=><Card key={message.id} style={message.sender?.role==='USER'?styles.userMessage:styles.staffMessage}><View style={styles.messageHead}><Text style={styles.author}>{message.sender?.role==='USER'?'You':'SocialConnect support'}</Text><Text style={styles.time}>{new Date(message.createdAt).toLocaleString()}</Text></View><Text style={styles.message}>{message.body}</Text></Card>)}{!['RESOLVED','CLOSED'].includes(selected.status)?<><Field placeholder="Write a reply…" multiline value={reply} onChangeText={setReply}/><Button title="Send reply" loading={busy} disabled={!reply.trim()} onPress={sendReply}/></>:<Card><Text style={styles.closed}>This request is {selected.status.toLowerCase()}.</Text></Card>}</Screen>;
  return <Screen scroll><Eyebrow>WE’RE HERE TO HELP</Eyebrow><Title subtitle="Account, payment, call and safety assistance">Help & support</Title><Card><Text style={styles.secure}>◆ Private support</Text><Text style={styles.help}>Replies stay inside SocialConnect. Never send passwords, OTP codes or full payment credentials.</Text></Card><SectionTitle>New request</SectionTitle><Field placeholder="Short subject" value={subject} onChangeText={setSubject}/><View style={styles.categories}>{categories.map(item=><Pressable key={item} onPress={()=>setCategory(item)} style={[styles.category,category===item&&styles.categoryActive]}><Text style={[styles.categoryText,category===item&&styles.categoryTextActive]}>{item.toLowerCase()}</Text></Pressable>)}</View><Field placeholder="Tell us what happened…" multiline value={body} onChangeText={setBody}/><Button title="Send support request" loading={busy} disabled={subject.trim().length<4||body.trim().length<10} onPress={create}/><SectionTitle>Your requests</SectionTitle>{tickets.length?tickets.map(ticket=><Pressable key={ticket.id} onPress={()=>setSelectedId(ticket.id)}><Card><View style={styles.ticketHead}><Text style={styles.ticketTitle}>{ticket.subject}</Text><Pill label={ticket.status} tone={ticket.status==='RESOLVED'?'success':'neutral'}/></View><Text style={styles.ticketMeta}>{ticket.category.toLowerCase()} · {ticket.messages.length} messages</Text></Card></Pressable>):<EmptyState icon="♡" title="No support requests" body="When you need us, start a private request above."/>}</Screen>;
}
const styles=StyleSheet.create({secure:{color:colors.primary,fontWeight:'900'},help:{color:colors.muted,lineHeight:20,marginTop:7},categories:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:spacing.md},category:{paddingHorizontal:11,paddingVertical:8,borderRadius:999,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},categoryActive:{backgroundColor:colors.primaryLight,borderColor:colors.primary},categoryText:{color:colors.muted,fontWeight:'700',fontSize:11,textTransform:'capitalize'},categoryTextActive:{color:colors.primary},ticketHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},ticketTitle:{flex:1,color:colors.text,fontWeight:'900',fontSize:15},ticketMeta:{color:colors.muted,fontSize:12,marginTop:7},messageHead:{flexDirection:'row',justifyContent:'space-between',gap:10},author:{color:colors.text,fontWeight:'900',fontSize:12},time:{color:colors.muted,fontSize:9},message:{color:colors.textSoft,lineHeight:20,marginTop:9},userMessage:{marginLeft:28,backgroundColor:colors.primaryLight},staffMessage:{marginRight:28},closed:{color:colors.muted,textAlign:'center'}});
